### ISSUE TITLE
USER STORY:  All Product View

### ISSUE THREAD

**Issue by naisepaul** [naisepaul/ManCrazeShoes#8]
As a **user** I want to be **able to view a list of all available products in the online** so that I can **search and choose shoes to purchase**

**Acceptance Criteria:**

- Given I am on the shop's homepage, When I click on the "New arrivals" link in the navigation menu, Then it goes to a dropdown menu and select the links I should be directed to a page displaying a paginated list of all available products.
- Given I am on the "All Products" page, When I scroll down, Then I should see a list of product cards, each containing:
The shoes brand
The shoe's image
The shoe's price
The shoe's size
An "Add to Cart" button
- Given I am on the "All Products" page, When I click on a product card, Then I should be directed to a product detail page where I can view more information about the selected product.

**Tasks:**

- [x]  Create a Django view for displaying all products.
- [x]  Create a template for the "All Products" page to render the list of products.
- [x]  Create a product model in the database with fields for brand, price, image, and size.
- [x]  Implement pagination for the list of products to display a reasonable number per page.
- [x]  Create a "All Products" link in the navigation menu that points to the "All Products" view.
- [x]  Ensure proper URL routing for the "All Products" page.
- [x]  Implement and style the product cards on the "All Products" page.
